### ISSUE TITLE
Org-mode clone

### ISSUE THREAD

**Issue by artelse** [rougier/org-bib-mode#1]
When I install `org-bib-mode` through cloning this repo through straight, I get an `org-mode` copy in my repo directory which is almost identical to my already installed `org`.
Is this on purpose?

**Comment by rougier** [comment]
Not all all. I guess this might be because [line 10](https://github.com/rougier/org-bib-mode/blob/master/org-bib-mode.el#L10) that straigth interprets. Can't you ask straight to not install dependencies?

**Comment by artelse** [comment]
Please see a discussion [here](https://www.reddit.com/r/emacs/comments/s6c1ga/straight_how_not_to_load_packagerequires/) that I started on the problem.
Apparently `org-mode` is not the right package to reference.

**Comment by rougier** [comment]
Thank, I just pushed a fix.

**Comment by artelse** [comment]
Fixed!
